## **NUMPY**

- Numerical Python
- **Library** of python
- Helps us create **N-Dimensional Arrays**
- Allows us to perform Numerical Computation/ Calculations
- 
- 
- 
- Matrix in High School - Pro SOON 

In [ ]:
import math

import sys

import os

In [2]:
import datetime

# Get today's date and current time

today = datetime.date.today()

current_time = datetime.datetime.now().time()

print(f"Today's Date: {today}, \nCurrent Time: {current_time}")

Today's Date: 2026-01-28, 
Current Time: 12:57:39.050524


### How to use this library

In [3]:
import numpy as np

np.__version__

'2.4.1'

In [4]:
# abstraction means - hide the unnecessary details
# just use what you need

### Objects that we create with numpy are `nd.arrays`
- like other objects we say 
- objects simply belong to a class
- TextIOWrapper object, Range Object, InstructorObject
- MappingObject
- 
- **ARRAYs**
- belong to nd.arrays

In [11]:
x = np.array(1)

# if you want to feed more than one number or characters into it, use sequence type data

type(x)

numpy.ndarray

We have another type of array in python as well
- we use Array module to create those arrays
- these arrays are fast
- only allow a single type of data - homogenous

In [ ]:
# we have an array module

from array import array

# a single type of data
nums = array('i',[1,2,3,4,5,6])
type(nums)



array.array

List has issues
- not as memory optimzed
- not as fast

With Numpy Arrays
- flexibility of lists
- fast operations and memory optimizations of arrays
- operations that Numpy has in its modules

In [17]:
# standard way of createing an array
python_list = [1,2,3,4,5]

array_1 = np.array(python_list)
print(python_list)
print(array_1)
type(array_1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

In [28]:
# N - Dimensions

# 1 Dimenstional Array
list_1D = [x for x in range(10)]

array_1D = np.array(list_1D)

print(array_1D, "\nnumber of dimension is: ",array_1D.ndim)

[0 1 2 3 4 5 6 7 8 9] 
number of dimension is:  1


In [29]:
# 2 Dimenstional Array
list_2D = [list_1D, list_1D]

array_2D = np.array(list_2D)

print(array_2D,"\nnumber of dimension is: ", array_2D.ndim)
print(list_2D)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]] 
number of dimension is:  2
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]


In [30]:
# 3 Dimenstional Array
list_3D = [list_2D, list_2D, list_2D]

array_3D = np.array(list_3D)

print(array_3D,"\nnumber of dimension is: ", array_3D.ndim)
print(list_3D)

[[[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]] 
number of dimension is:  3
[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]


In [33]:
array_1D.ndim #

list_1D.ndim # 

AttributeError: 'list' object has no attribute 'ndim'

### Array Attributes/Properties
- .ndim - number of dimensions
- .shape - ( rows , columns )
- .size - how many elemetns
- .dtype - type of data stored in array
- 

In [41]:
array_2D.ndim # dimensions


# shape ==== ( rows , columns )
array_1D.shape
array_2D.shape
array_3D.shape

array_2D.dtype

dtype('int64')

In [ ]:
array_fruits = np.array(['apple', 'banana', 'orange'])

array_fruits.

dtype('<U6')